Snittlistan.Web/Areas/V2/ViewModels/AbsenceViewModel.cs
using Snittlistan.Web.Areas.V2.Domain;

namespace Snittlistan.Web.Areas.V2.ViewModels;
public class AbsenceViewModel
{
    public AbsenceViewModel(Absence absence, Player player)
    {
        PlayerName = player.Name;
        From = absence.From;
        To = absence.To;
    }

    public string PlayerName { get; private set; }

    public DateTime From { get; private set; }

    public DateTime To { get; private set; }
}

Snittlistan.Web/Areas/V2/Controllers/AbsenceController.cs
#nullable enable

using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using Raven.Client.Util;
using Snittlistan.Web.Areas.V2.Domain;
using Snittlistan.Web.Areas.V2.Indexes;
using Snittlistan.Web.Areas.V2.ViewModels;
using Snittlistan.Web.Controllers;

namespace Snittlistan.Web.Areas.V2.Controllers;

public class AbsenceController : AbstractController
{
    [Authorize(Roles = WebsiteRoles.Absence.View)]
    public ActionResult Index()
    {
        return View();
    }

    [ChildActionOnly]
    public ActionResult AbsenceTable(bool? hideControls)
    {
        ViewBag.HideControls = hideControls.GetValueOrDefault();
        AbsenceIndex.Result[] absences = CompositionRoot.DocumentSession.Query<AbsenceIndex.Result, AbsenceIndex>()
            .Where(x => x.To >= SystemTime.UtcNow.Date.AddDays(-1))
            .OrderBy(p => p.To)
            .ThenBy(p => p.PlayerName)
            .ProjectFromIndexFieldsInto<AbsenceIndex.Result>()
            .ToArray();
        return View(absences);
    }

    public ActionResult Create()
    {
        ViewBag.Player = CompositionRoot.DocumentSession.CreatePlayerSelectList();
        return View(new CreateAbsenceViewModel());
    }

    [HttpPost]
    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Edit(int id, CreateAbsenceViewModel vm)
    {
        if (ModelState.IsValid == false)
        {
            ViewBag.Player = CompositionRoot.DocumentSession.CreatePlayerSelectList();
            return View(vm);
        }

        Absence absence = CompositionRoot.DocumentSession.Load<Absence>(id);
        absence.Player = vm.Player;
        absence.From = vm.From;
        absence.To = vm.To;
        absence.Comment = vm.Comment;
        return RedirectToAction("Index");
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    [HttpPost]
    public ActionResult Create(CreateAbsenceViewModel vm)
    {
        if (ModelState.IsValid == false)
        {
            ViewBag.Player = CompositionRoot.DocumentSession.CreatePlayerSelectList();
            return View(vm);
        }

        Absence absence = Absence.Create(vm.From, vm.To, vm.Player, vm.Comment);
        CompositionRoot.DocumentSession.Store(absence);

        return RedirectToAction("Index");
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Edit(int id)
    {
        Absence absence = CompositionRoot.DocumentSession.Load<Absence>(id);
        if (absence == null)
        {
            throw new HttpException(404, "Absence not found");
        }

        ViewBag.Player = CompositionRoot.DocumentSession.CreatePlayerSelectList(absence.Player);
        return View(new CreateAbsenceViewModel(absence));
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Delete(int id)
    {
        Absence absence = CompositionRoot.DocumentSession.Include<Absence>(x => x.Player).Load<Absence>(id);
        if (absence == null)
        {
            return RedirectToAction("Index");
        }

        Player player = CompositionRoot.DocumentSession.Load<Player>(absence.Player);
        return View(new AbsenceViewModel(absence, player));
    }

    [HttpPost]
    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    [ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        Absence absence = CompositionRoot.DocumentSession.Load<Absence>(id);
        if (absence == null)
        {
            throw new HttpException(404, "Absence not found");
        }

        CompositionRoot.DocumentSession.Delete(absence);
        return RedirectToAction("Index");
    }

    public class CreateAbsenceViewModel : IValidatableObject
    {
        public CreateAbsenceViewModel()
        {
            Comment = string.Empty;
        }

        public CreateAbsenceViewModel(Absence absence)
        {
            DateRange =
                absence.From != absence.To
                ? $"{absence.From.ToShortDateString()} - {absence.To.ToShortDateString()}"
                : $"{absence.From.ToShortDateString()}";
            Player = absence.Player;
            Comment = absence.Comment;
        }

        public DateTime From { get; set; }

        public DateTime To { get; set; }

        [Required]
        [Display(Name = "Datum:")]
        public string DateRange { get; set; } = null!;

        [Required]
        public string Player { get; set; } = null!;

        public string Comment { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            string[] rangeSplit = DateRange.Split(new[] { " - " }, StringSplitOptions.RemoveEmptyEntries);
            if (rangeSplit.Length > 0)
            {
                From = To = DateTime.Parse(rangeSplit[0]);
                if (rangeSplit.Length == 2)
                {
                    To = DateTime.Parse(rangeSplit[1]);
                }
            }

            if (To < SystemTime.UtcNow.Date)
            {
                yield return new ValidationResult("Till-datum kan inte vara passerade datum");
            }

            if (From > To)
            {
                yield return new ValidationResult("Från-datum kan inte vara före till-datum");
            }

            if (From.Year != To.Year)
            {
                yield return new ValidationResult("Frånvaro kan inte gå över flera år");
            }

            if (Comment != null && Comment.Length > 160)
            {
                yield return new ValidationResult("Kommentar kan vara högst 160 tecken");
            }
        }
    }
}

Snittlistan.Web/Areas/V2/Views/Absence/AbsenceTable.cshtml
@model Snittlistan.Web.Areas.V2.Indexes.AbsenceIndex.Result[]
@{
    Layout = null;
    var hideControls = ViewBag.HideControls;
}

<div class="row">
    <div class="span12">
        <table class="table table-condensed table-striped">
            <tr>
                <th>Namn</th>
                <th></th>
                @if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false)
                {
                    <th></th>
                    <th></th>
                }
            </tr>
            @foreach (var absence in Model)
            {
                <tr>
                    @{
                        var rowspan = string.IsNullOrWhiteSpace(absence.Comment) ? 1 : 2;
                    }
                    <td class="center" rowspan="@rowspan">@absence.PlayerName</td>
                    <td>
                        @Html.FormatDateSpan(absence.From, absence.To)
                    </td>

                    @if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false)
                    {
                        <td class="center" rowspan="@rowspan">
                            <a href="@Url.Action("Edit", new { id = absence.Id.Substring(absence.Id.LastIndexOf('-') + 1) })">
                                <i class="sprite-glyphicons_151_edit"></i>
                            </a>
                        </td>
                        <td class="center" rowspan="@rowspan">
                            <a href="@Url.Action("Delete", new { id = absence.Id.Substring(absence.Id.LastIndexOf('-') + 1) })">
                                <i class="sprite-glyphicons_016_bin"></i>
                            </a>
                        </td>
                    }
                </tr>
                if (string.IsNullOrWhiteSpace(absence.Comment) == false)
                {
                    <tr>
                        <td>@absence.Comment</td>
                    </tr>
                }
            }
        </table>
    </div>
</div>

Snittlistan.Web/Areas/V2/Views/Absence/Create.cshtml
@model Snittlistan.Web.Areas.V2.Controllers.AbsenceController.CreateAbsenceViewModel

<div class="row">
    <div class="span12">
        @using (Html.BeginForm("Create", "Absence", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
        {
            <fieldset>
                <legend>Registrera frånvaro</legend>
            </fieldset>
            @Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary")
            @Html.Partial("_AbsenceEditor", Model)
            <div class="form-actions">
                <button class="btn btn-primary btn-large" type="submit">Spara</button>
                @Html.ActionLink("Avbryt", "Index", null, new
                {
                    @class = "btn btn-large"
                })
            </div>
        }
    </div>
</div>


Snittlistan.Web/Areas/V2/Views/Absence/Delete.cshtml
@model AbsenceViewModel

@{
    ViewBag.Title = "Ta bort";
}

<h4>Ta bort</h4>
<p>Är du säker på att du vill ta bort denna registrerade frånvaro?</p>
@using (Html.BeginForm("Delete", "Absence", FormMethod.Post))
{
    <h3>@Model.PlayerName <em>(@Html.FormatDateSpan(Model.From, Model.To))</em></h3>
    <button class="btn btn-danger btn-large" type="submit">Ta bort</button>
    @Html.ActionLink("Avbryt", "Index", null, new { @class = "btn btn-large" })
}

Snittlistan.Web/Areas/V2/Views/Absence/Edit.cshtml
@model Snittlistan.Web.Areas.V2.Controllers.AbsenceController.CreateAbsenceViewModel

@{
    ViewBag.Title = "Redigera frånvaro";
}

<div class="row">
    <div class="span8">
        <h4>@ViewBag.Title</h4>
        @using (Html.BeginForm("Edit", "Absence", FormMethod.Post, new { @class = "form-horizontal"}))
        {
            @Html.DisplayFor(model => Html.ViewData.ModelState, "ValidationSummary")
            @Html.Partial("_AbsenceEditor", Model)
            <div class="form-actions">
                <button class="btn btn-primary btn-large" type="submit">Spara</button>
                @Html.ActionLink("Avbryt", "Index", null, new { @class = "btn btn-large" })
            </div>
        }
    </div>
</div>

Snittlistan.Web/Areas/V2/Views/Absence/Index.cshtml
@model Snittlistan.Web.Areas.V2.Indexes.AbsenceIndex.Result[]

<div class="row">
    <div class="span8">
        <h4 class="pull-left">Anmäld frånvaro</h4>
        @if (User.IsInRole2(WebsiteRoles.Uk.UkTasks))
        {
            <a class="pull-right" href="@Url.Action("Create")">
                <i class="sprite-glyphicons_006_user_add"></i>
                Registrera frånvaro
            </a>
        }
        <div class="clearfix"></div>
    </div>
</div>
@Html.Action("AbsenceTable")

Snittlistan.Web/Areas/V2/Views/Absence/_AbsenceEditor.cshtml
@model Snittlistan.Web.Areas.V2.Controllers.AbsenceController.CreateAbsenceViewModel

<div class="control-group">
    <label class="control-label" for="player">Spelare:</label>
    <div class="controls">
        @Html.DropDownList("Player", null, new { required = "required", id = "player" })
    </div>
</div>
<div class="control-group">
    @Html.LabelFor(x => x.DateRange, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBoxFor(
            x => x.DateRange,
            new
            {
                @class = "date-picker",
                @readonly = "readonly",
                required = "required",
                placeholder = "Välj datum",
                data_datepicker = "",
                data_range = "true",
                data_multiple_dates_separator =" - "
            })
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="comment">Kommentar:</label>
    <div class="controls">
        <input type="text"
               name="comment"
               id="comment"
               maxlength="160"
               value="@Model.Comment" />
    </div>
</div>