Snittlistan.Web/Areas/V2/ViewModels/ActivityViewModel.cs
using System.Web;

namespace Snittlistan.Web.Areas.V2.ViewModels;
public class ActivityViewModel
{
    public ActivityViewModel(
        string id,
        string title,
        DateTime date,
        string messageHtml,
        string author,
        string appleTouchIcon,
        string fullTeamName)
    {
        Id = id;
        Title = title;
        ActivityDate = date;
        MessageHtml = new HtmlString(messageHtml);
        Author = author;
        AppleTouchIcon = appleTouchIcon;
        FullTeamName = fullTeamName;
    }

    public string Id { get; }

    public string Title { get; }

    public DateTime ActivityDate { get; }

    public IHtmlString MessageHtml { get; }

    public string Author { get; }

    public string AppleTouchIcon { get; }

    public string FullTeamName { get; }
}

Snittlistan.Web/Areas/V2/ViewModels/RosterHeaderViewModel.cs
using Snittlistan.Web.Areas.V2.Domain;

#nullable enable

namespace Snittlistan.Web.Areas.V2.ViewModels;
public class RosterHeaderViewModel
{
    public RosterHeaderViewModel()
    {
    }

    public RosterHeaderViewModel(
        string? rosterId,
        string? team,
        string? teamLevel,
        string? location,
        string? opponent,
        DateTime date,
        OilPatternInformation oilPattern,
        string? matchResultId,
        bool matchTimeChanged)
    {
        RosterId = rosterId;
        Team = team;
        TeamLevel = teamLevel;
        Location = location;
        Opponent = opponent;
        Date = date;
        OilPattern = oilPattern;
        MatchResultId = matchResultId;
        MatchTimeChanged = matchTimeChanged;
    }

    public string? RosterId { get; set; }

    public string? Team { get; set; }

    public string? TeamLevel { get; set; }

    public string? Location { get; set; }

    public string? Opponent { get; set; }

    public DateTime Date { get; set; }

    public OilPatternInformation? OilPattern { get; set; }

    public string? MatchResultId { get; set; }

    public bool MatchTimeChanged { get; set; }
}

Snittlistan.Web/Areas/V2/ViewModels/RosterViewModel.cs
#nullable enable

using Snittlistan.Web.Areas.V2.Domain;

namespace Snittlistan.Web.Areas.V2.ViewModels;

public class RosterViewModel
{
    public RosterViewModel()
    {
        Players = new List<PlayerItem>();
    }

    public RosterViewModel(
        Roster roster,
        PlayerItem? teamLeader,
        List<PlayerItem> players)
    {
        TeamLeader = teamLeader;
        Players = players;
        Season = roster.Season;
        Turn = roster.Turn;
        IsFourPlayer = roster.IsFourPlayer;
        Preliminary = roster.Preliminary;
        Header = new RosterHeaderViewModel(
            roster.Id,
            roster.Team,
            roster.TeamLevel,
            roster.Location,
            roster.Opponent,
            roster.Date,
            roster.OilPattern,
            roster.MatchResultId,
            roster.MatchTimeChanged);
    }

    public RosterHeaderViewModel? Header { get; set; }

    public int Season { get; set; }

    public int Turn { get; set; }

    public bool IsFourPlayer { get; set; }

    public bool Preliminary { get; set; }

    public List<PlayerItem> Players { get; set; }

    public PlayerItem? TeamLeader { get; set; }

    public class PlayerItem
    {
        public PlayerItem(string playerId, string playerName, bool accepted)
        {
            PlayerId = playerId;
            PlayerName = playerName;
            Accepted = accepted;
        }

        public string PlayerId { get; }
        public string PlayerName { get; }
        public bool Accepted { get; }
    }
}

Snittlistan.Web/Models/Roster.cs
namespace Snittlistan.Web.Models
{
    using System;

    public class Roster
    {
        public Roster(int season, int turn, string team, string location, string opponent, DateTime date)
        {
            Season = season;
            Turn = turn;
            Team = team;
            Location = location;
            Opponent = opponent;
            Date = date;
        }

        public int Id { get; set; }

        public int Season { get; set; }

        public int Turn { get; set; }

        public string Team { get; set; }

        public string Location { get; set; }

        public string Opponent { get; set; }

        public DateTime Date { get; set; }
    }
}

Snittlistan.Web/Areas/V2/Controllers/RosterController.cs
#nullable enable

using Raven.Abstractions;
using Raven.Client;
using Rotativa;
using Rotativa.Options;
using Snittlistan.Web.Areas.V2.Domain;
using Snittlistan.Web.Areas.V2.Indexes;
using Snittlistan.Web.Areas.V2.ViewModels;
using Snittlistan.Web.Commands;
using Snittlistan.Web.Controllers;
using Snittlistan.Web.Helpers;
using Snittlistan.Web.Infrastructure;
using Snittlistan.Web.Infrastructure.Bits;
using Snittlistan.Web.Models;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace Snittlistan.Web.Areas.V2.Controllers;

public class RosterController : AbstractController
{
    private const string DateTimeFormat = "yyyy-MM-dd HH:mm";
    private readonly IBitsClient bitsClient;

    public RosterController(IBitsClient bitsClient)
    {
        this.bitsClient = bitsClient;
    }

    public ActionResult Index(int? season)
    {
        bool selectAll = true;
        if (season.HasValue == false)
        {
            season = CompositionRoot.DocumentSession.LatestSeasonOrDefault(SystemTime.UtcNow.Year);
            selectAll = false;
        }

        Roster[] rosters = CompositionRoot.DocumentSession.Query<Roster, RosterSearchTerms>()
            .Where(r => r.Season == season)
            .ToArray();
        InitialDataViewModel.SelectedTurn[] selectedTurns =
            Array.Empty<InitialDataViewModel.SelectedTurn>();
        if (User?.CustomIdentity.PlayerId is not null)
        {
            Roster[] futureRosters = rosters
                .Where(x => x.Preliminary == false
                    && x.Date.AddDays(1).Date > SystemTime.UtcNow.ToLocalTime()
                    && x.Players.Contains(User.CustomIdentity.PlayerId))
                .ToArray();
            selectedTurns = futureRosters
                .GroupBy(x => x.Turn)
                .Select(x => new InitialDataViewModel.SelectedTurn(
                    x.Key,
                    x.All(r => r.AcceptedPlayers.Contains(User.CustomIdentity.PlayerId))))
                .ToArray();
        }

        IEnumerable<InitialDataViewModel.TurnViewModel> q =
            from roster in rosters
            orderby roster.Turn
            group roster by roster.Turn
                into g
            let lastDate = g.Max(x => x.Date)
            where selectAll || lastDate >= SystemTime.UtcNow.Date
            select new InitialDataViewModel.TurnViewModel(
                seasonStart: season.Value,
                turn: g.Key,
                startDate: g.Min(x => x.Date),
                endDate: lastDate,
                rosters: g.Select(x => new RosterViewModel(
                               x,
                               new RosterViewModel.PlayerItem(string.Empty, string.Empty, false),
                               new List<RosterViewModel.PlayerItem>()))
                           .SortRosters()
                           .ToArray());
        InitialDataViewModel.TurnViewModel[] turns = q.ToArray();
        IEnumerable<InitialDataViewModel.ScheduledItem> activities =
            CompositionRoot.DocumentSession.Query<Activity, ActivityIndex>()
                           .Where(x => x.Season == season.Value)
                           .ToArray()
                           .Where(x => selectAll || x.Date >= SystemTime.UtcNow.Date.AddDays(-3))
                           .Select(x => new InitialDataViewModel.ScheduledActivityItem(
                               x.Id!,
                               x.Title,
                               x.Date,
                               x.MessageHtml,
                               string.IsNullOrEmpty(x.AuthorId) == false
                               ? CompositionRoot.DocumentSession.Load<Player>(x.AuthorId)?.Name ?? string.Empty
                               : string.Empty,
                               CompositionRoot.CurrentTenant.AppleTouchIcon,
                               CompositionRoot.CurrentTenant.TeamFullName));
        bool isFiltered = rosters.Length != turns.Sum(x => x.Rosters.Length);
        InitialDataViewModel vm = new(
            selectedTurns,
            turns.Concat(activities).OrderBy(x => x.Date).ToArray(),
            season.Value,
            isFiltered);

        return turns.Length <= 0 ? View("Unscheduled", vm) : View(vm);
    }

    public ActionResult Results()
    {
        return RedirectToAction("Index");
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult CreateBits()
    {
        return View();
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    [HttpPost]
    public async Task<ActionResult> CreateBitsVerify(VerifyBitsViewModel vm)
    {
        if (CompositionRoot.DocumentSession.Query<Roster, RosterSearchTerms>()
            .SingleOrDefault(x => x.BitsMatchId == vm.BitsMatchId) != null)
        {
            ModelState.AddModelError("BitsMatchId", "Matchen redan upplagd");
        }

        if (ModelState.IsValid == false)
        {
            return View("CreateBits");
        }

        int season = CompositionRoot.DocumentSession.LatestSeasonOrDefault(DateTime.Now.Year);
        WebsiteConfig websiteConfig = CompositionRoot.DocumentSession.Load<WebsiteConfig>(WebsiteConfig.GlobalId);
        Infrastructure.Bits.Contracts.HeadInfo content = await bitsClient.GetHeadInfo(vm.BitsMatchId);
        ParseHeaderResult header = BitsParser.ParseHeader(content, websiteConfig.ClubId);
        ViewBag.TeamNamesAndLevels = websiteConfig.TeamNamesAndLevels;
        return View(
            "Create", new CreateRosterViewModel
            {
                Season = season,
                Turn = header.Turn,
                BitsMatchId = vm.BitsMatchId,
                Team = header.Team,
                IsFourPlayer = false,
                Opponent = header.Opponent,
                Date = header.Date.ToString(DateTimeFormat),
                Location = header.Location,
                OilPatternName = header.OilPattern.Name,
                OilPatternUrl = header.OilPattern.Url
            });
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Create()
    {
        WebsiteConfig websiteConfig = CompositionRoot.DocumentSession.Load<WebsiteConfig>(WebsiteConfig.GlobalId);
        ViewBag.TeamNamesAndLevels = websiteConfig.TeamNamesAndLevels;
        CreateRosterViewModel vm = new()
        {
            Season = CompositionRoot.DocumentSession.LatestSeasonOrDefault(DateTime.Now.Year)
        };
        return View(vm);
    }

    [HttpPost]
    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Create(CreateRosterViewModel vm)
    {
        if (!ModelState.IsValid)
        {
            return View(vm);
        }

        Roster roster = new(
            vm.Season,
            vm.Turn,
            vm.BitsMatchId,
            vm.Team.Split(';')[0],
            vm.Team.Split(';')[1],
            vm.Location,
            vm.Opponent,
            ParseDate(vm.Date),
            vm.IsFourPlayer,
            new OilPatternInformation(vm.OilPatternName!, vm.OilPatternUrl!))
        {
            ManuallyAdded = true
        };
        CompositionRoot.DocumentSession.Store(roster);
        return RedirectToAction("Index");
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Edit(string id)
    {
        Roster roster = CompositionRoot.DocumentSession.Load<Roster>(id);
        if (roster == null)
        {
            throw new HttpException(404, "Roster not found");
        }

        if (roster.MatchResultId != null)
        {
            throw new HttpException(400, "Can not modify registered rosters");
        }

        WebsiteConfig websiteConfig = CompositionRoot.DocumentSession.Load<WebsiteConfig>(WebsiteConfig.GlobalId);
        ViewBag.TeamNamesAndLevels = websiteConfig.TeamNamesAndLevels;
        return View(new CreateRosterViewModel(roster));
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    [HttpPost]
    public ActionResult Edit(string id, CreateRosterViewModel vm)
    {
        WebsiteConfig websiteConfig = CompositionRoot.DocumentSession.Load<WebsiteConfig>(WebsiteConfig.GlobalId);
        if (!ModelState.IsValid)
        {
            ViewBag.TeamNamesAndLevels = websiteConfig.TeamNamesAndLevels;
            return View(vm);
        }

        Roster roster = CompositionRoot.DocumentSession.Load<Roster>(id);
        if (roster == null)
        {
            throw new HttpException(404, "Roster not found");
        }

        if (roster.MatchResultId != null)
        {
            throw new HttpException(400, "Can not modify registered rosters");
        }

        roster.Location = vm.Location;
        roster.Opponent = vm.Opponent;
        roster.Season = vm.Season;
        roster.Team = vm.Team.Split(';')[0];
        roster.TeamLevel = vm.Team.Split(';')[1];
        roster.Turn = vm.Turn;
        roster.BitsMatchId = vm.BitsMatchId;
        roster.IsFourPlayer = vm.IsFourPlayer;
        roster.Date = ParseDate(vm.Date);
        if (vm.BitsMatchId == 0)
        {
            roster.OilPattern = new OilPatternInformation(vm.OilPatternName!, string.Empty);
        }

        return RedirectToAction("Index");
    }

    [Authorize(Roles = WebsiteRoles.Uk.UkTasks)]
    public ActionResult Delete(string id)
    {
        Roster roster = CompositionRoot.DocumentSession.Load<Roster>(id);
        if (roster == null)
        {
            throw new HttpException(404, "Roster not found");
        }

        if (roster.MatchResultId != null)
        {
            throw new HttpException(400, "Can not delete registered rosters");
        }


Snittlistan.Web/Areas/V2/Views/Shared/DisplayTemplates/ActivityViewModel.cshtml
@using Raven.Abstractions
@model ActivityViewModel

@{
    var showViewMoreLink = Convert.ToBoolean(ViewData["showViewMoreLink"]);
    var showComments = Convert.ToBoolean(ViewData["showComments"]);
}

<div class="row">
    <div class="span12">
        <div class="well well-small activity-container">
            <img class="activity-image"
                 src="@Url.ContentCacheBreak($"~/Content/css/images/{Model.AppleTouchIcon}")"
                 alt="@Model.FullTeamName" />
            <div class="activity-content-container">
                <h4 class="activity-main-title">
                    @Model.Title
                    <em>
                        (<time datetime="@($"{Model.ActivityDate:s}")">@Model.ActivityDate.ToString("d MMMM HH:mm")</time>)
                    </em>
                    @if (Model.ActivityDate.ToUniversalTime() < SystemTime.UtcNow)
                    {
                        <span class="label label-important">PASSERAT</span>
                    }
                </h4>
                <h5 class="activity-sub-title">
                    @Model.Author
                </h5>
                @if (showViewMoreLink)
                {
                    <div class="cropped-message-well">@Model.MessageHtml</div>
                    @Html.ActionLink("Visa mer", "Index", "ActivityDetails", null, null, "disqus_thread", new { Model.Id }, null)
                }
                else
                {
                    <div>@Model.MessageHtml</div>
                }
            </div>
        </div>
    </div>
</div>
@if (showComments)
{
    <div class="row">
        <div class="span12">
            <div id="disqus_thread"></div>
            <script>
                /**
                 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                /*
                var disqus_config = function () {
                this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                };
                */
                (function () { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://snittlistan.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>
    </div>
}

Snittlistan.Web/Areas/V2/Views/Shared/DisplayTemplates/ResultSeriesReadModel.cshtml
@using System.Globalization
@using Snittlistan.Web.Areas.V2.ReadModels
@model Snittlistan.Web.Areas.V2.ReadModels.ResultSeriesReadModel

@{
    ViewBag.Title = "Result";
}

<h3>Resultat</h3>
<table class="table table-condensed table-bordered table-striped">
    <tr>
        <td>#</td>
        <td>Namn</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>Tot</td>
        <td>Banp</td>
    </tr>
    @{
        var row = 1;
    }
    @foreach (KeyValuePair<string, List<ResultSeriesReadModel.PlayerGame>[]> player in Model.SortedPlayers())
    {
        <tr>
            <td>@(row++)</td>
            <td>@player.Key</td>
            @for (var serie = 0; serie < 4; serie++)
            {
                <td>
                    @{
                        List<ResultSeriesReadModel.PlayerGame> game = player.Value[serie];
                    }
                    @string.Join("+", game.Select(x => x.Pins.ToString(CultureInfo.InvariantCulture)))
                </td>
            }
            <td>
                @player.Value.SelectMany(x => x).Sum(x => x.Pins)
            </td>
            <td>
                @player.Value.SelectMany(x => x).Sum(x => x.Score)
            </td>
        </tr>
    }
    <tr>
        <td colspan="2"></td>
        <td>@Model.SerieSum(0)</td>
        <td>@Model.SerieSum(1)</td>
        <td>@Model.SerieSum(2)</td>
        <td>@Model.SerieSum(3)</td>
        <td>@Model.Total()</td>
        <td></td>
    </tr>
</table>

Snittlistan.Web/Areas/V2/Views/Shared/DisplayTemplates/RosterHeaderViewModel.cshtml
@model RosterHeaderViewModel

<dl class="dl-horizontal">
<dt>lag</dt>
<dd>@Content.TeamLabel(Model.TeamLevel, Model.Team)</dd>
    <dt>plats</dt>
    <dd>@Model.Location</dd>
    <dt>motstånd</dt>
    <dd>@Model.Opponent</dd>
    @if (string.IsNullOrWhiteSpace(Model.OilPattern.Name) == false)
    {
        <dt>oljeprofil</dt>
        <dd>
            @if (string.IsNullOrWhiteSpace(Model.OilPattern.Url) == false)
            {
                <a href="@Model.OilPattern.Url">
                    @Model.OilPattern.Name
                    <i class="icon-share-alt"></i>
                </a>
            }
            else
            {
                @Model.OilPattern.Name
            }
        </dd>
    }

    <dt>när</dt>
    <dd>
        <em>
            <time datetime="@Model.Date.ToString("s")">
                @Model.Date.ToString("dddd d MMMM HH:mm")
            </time>
        </em>
        @if (Model.MatchTimeChanged)
        {
            <span class="label label-important">FLYTTAD</span>
        }
    </dd>
</dl>

Snittlistan.Web/Areas/V2/Views/Shared/DisplayTemplates/RosterViewModel.cshtml
@model RosterViewModel
@{
    var hideControls = Convert.ToBoolean(ViewData["hideControls"]);
}

<div class="well well-small editable">
    @if (User.IsInRole2(WebsiteRoles.Uk.UkTasks) && hideControls == false && Model.Header.MatchResultId == null)
    {
        <div class="dropdown edit-left">
            <button class="dropdown-toggle" data-toggle="dropdown">
                <i class="sprite-glyphicons_019_cogwheel"></i>
                <b class="caret"></b>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("Edit", "Roster", new { id = Model.Header.RosterId })">
                        <i class="sprite-glyphicons_151_edit"></i>
                        Redigera
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Delete", "Roster", new { id = Model.Header.RosterId })">
                        <i class="sprite-glyphicons_016_bin"></i>
                        Ta bort
                    </a>
                </li>
            </ul>
        </div>
    }
    @Html.DisplayFor(x => x.Header)
</div>

Snittlistan.Web/Areas/V2/Views/Shared/DisplayTemplates/ValidationSummary.cshtml
@model ModelStateDictionary

@{
    var message = ViewData["message"] as string ?? "Det gick inte att spara. Försök gärna igen.";
}

@if (Html.ViewData.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        @Html.ValidationSummary(false, message)
    </div>
}